MilkTeaECommerce/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MilkTeaECommerce.Data;
using MilkTeaECommerce.Models;
using MilkTeaECommerce.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MilkTeaECommerce.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ShopController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? page)
        {
            int num = 9;
            var lstShop = _context.Shops.Include(x => x.ApplicationUser).Where(x => x.IsConfirm == true);
                
            int shopCount = lstShop.Count();
            // điều kiện để phân trang
            if (page != null && page > 0)
            {
                int numpage = shopCount % num == 0 ? shopCount / num : (shopCount / num) + 1;

                // trang cuoi +1
                if(page>numpage)
                {
                    return RedirectToAction();
                }
                ViewBag.page = page;
                // nếu là trang cuối và là rơi vào trường hơp 2
                if (page >= numpage && shopCount % num != 0)
                {
                    // lấy số lẻ
                    lstShop = lstShop.Skip(num * (numpage - 1)).Take(shopCount % num);

                }
                //trường hợp 1
                else
                {

                    lstShop = lstShop.Skip(num * (page.GetValueOrDefault() - 1)).Take(num);
                }
            }
            else
            {
                ViewBag.page = 1;
                lstShop = lstShop.Take(9);
            }
            // chuyển product thành ProductViewModel
            var obj = lstShop
                .Select(x => new ShopViewModel
                {
                    Id = x.ApplicationUserId,
                    Name = x.Name,
                    ImgUrl = x.ImgUrl,
                    Address = x.ApplicationUser.Address

                }).ToList();
            return View(obj);
        }
        [HttpGet]
        public IActionResult Details(string id,int? page)
        {
            if (id == null)
            {
                return NotFound();
            }
            
             var shop = _context.Shops.Include(x=>x.ApplicationUser).Where(x => x.ApplicationUserId == id).SingleOrDefault();
            if (shop == null)
            {
                return NotFound();
            }
            ViewBag.IdShop = shop.ApplicationUserId;
            ViewBag.NameShop = shop.Name;
            ViewBag.DeShop = shop.Description;
            ViewBag.Image = shop.ImgUrl;
            ViewBag.Address = shop.ApplicationUser.Address;

            int num = 9;
            var lstProduct = _context.Products.Where(x => x.ShopId==id && x.IsConfirm==true);

            int procount = lstProduct.Count();
            // điều kiện để phân trang
            if (page != null && page > 0)
            {
                int numpage = procount % num == 0 ? procount / num : (procount / num) + 1;

                // trang cuoi +1
                if (page > numpage)
                {
                    ViewBag.page = numpage;
                }
                else
                {
                    ViewBag.page = page;
                }
                // nếu là trang cuối và là rơi vào trường hơp 2
                if (page >= numpage && procount % num != 0)
                {
                    // lấy số lẻ
                    lstProduct = lstProduct.Skip(num * (numpage - 1)).Take(procount % num);

                }
                //trường hợp 1
                else
                {

                    lstProduct = lstProduct.Skip(num * (page.GetValueOrDefault() - 1)).Take(num);
                }
            }
            else
            {
                ViewBag.page = 1;
                lstProduct = lstProduct.Take(9);
            }
            // chuyển product thành ProductViewModel
            var obj = lstProduct
                .Select(x => new ProductViewUserModel
                {
                    ProductId = x.Id,
                    ProductName = x.Name,
                    ProductImgUrl = x.ImageUrl,
                    Price = x.Price.GetValueOrDefault(),
                    OldPrice=x.Price.GetValueOrDefault()*2
                }).ToList();
            return View(obj);
        }

        // api
        [HttpGet]
        public IActionResult getshop(string id)
        {
            var shop = _context.Shops.Include(x => x.ApplicationUser).Where(x => x.ApplicationUserId == id).Select(x => new
            {
                Id=x.ApplicationUserId,
                Name=x.Name,
                Des=x.Description,
                Image=x.ImgUrl,
                Address=x.ApplicationUser.Address
            }).SingleOrDefault();
            return Json(shop);
        }
        [HttpGet]
        public IActionResult getproducts(string idShop)
        {
            var products = _context.Products.Where(x => x.ShopId == idShop && x.IsConfirm== true).Select(x => new
            {
                Id=x.Id,
                Name=x.Name,
                Price=x.Price.GetValueOrDefault().ToString("#,###"),
                Image=x.ImageUrl
            });
            return Json(products);
        }
    }
}

MilkTeaECommerce/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using MilkTeaECommerce.Data;
using MilkTeaECommerce.Models;
using MilkTeaECommerce.Models.Models;

namespace MilkTeaECommerce.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly IHostEnvironment _hostEnvironment;
        public UserController(ApplicationDbContext db,SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IEmailSender emailSender, IHostEnvironment hostEnvironment)
        {
            _db = db;
            _signInManager = signInManager;
            _userManager = userManager;
            _emailSender = emailSender;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Profile");
        }

        [HttpGet]
        public async Task<IActionResult>Profile()
        {
            var user = await _userManager.GetUserAsync(User);
            var profile = new ProfileViewModel();
            profile.Email = user.Email;
            profile.Username = user.UserName;
            profile.Name = user.Name;
            profile.Phonenumber = user.PhoneNumber;
            profile.ImageUrl = user.ImageUrl;
            profile.Address = user.Address;
            profile.IsMailComfirm = user.EmailConfirmed;
            profile.IsPhoneComfirm = user.PhoneNumberConfirmed;
            return View(profile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile(ProfileViewModel vm)
        {
            if(ModelState.IsValid)
            {
                string fileName = "";
                string folderName = "wwwroot\\Media\\";
                string webRootPath = _hostEnvironment.ContentRootPath;
                string newPath = Path.Combine(webRootPath, folderName);
                if (!Directory.Exists(newPath))
                {
                    Directory.CreateDirectory(newPath);
                }
                if (vm.file != null)
                {
                    fileName = ContentDispositionHeaderValue.Parse(vm.file.ContentDisposition).FileName.Trim('"');
                    string fullPath = Path.Combine(newPath, fileName);
                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        vm.file.CopyTo(stream);

                    }
                }
                var user = await _userManager.GetUserAsync(User);
                user.Name = vm.Name;
                user.Address = vm.Address;
                if(vm.Email.ToLower() != user.Email.ToLower())
                {
                    user.UserName = vm.Email;
                    user.Email = vm.Email;
                    user.EmailConfirmed = false;
                }  
                if(vm.Phonenumber!=user.PhoneNumber)
                {
                    user.PhoneNumber = vm.Phonenumber;
                    user.PhoneNumberConfirmed = false;
                }
                if(fileName!="")
                {
                    user.ImageUrl =@"/Media/"+ fileName;
                    vm.ImageUrl = user.ImageUrl;
                }    
                try
                {
                    _db.AspNetUsers.Update(user);
                    _db.SaveChanges();
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                    
                }
            }
            return View(vm);
        }
        public async Task<IActionResult> OrderDetail()
        {
            var user = await _userManager.GetUserAsync(User);
            var obj = _db.OrderDetails.Include(x => x.Product).ThenInclude(x => x.Shop)
                .Include(x => x.DeliveryDetails).ThenInclude(x => x.Delivery).Where(x=>x.OrderHeader.ApplicationUserId == user.Id)
                .Select(x => new OrderDetailUserViewModel()
                {
                    shopimage = x.Product.Shop.ImgUrl,
                    shopid = x.Product.Shop.ApplicationUserId,
                    shopname = x.Product.Shop.Name,
                    productimage = x.Product.ImageUrl,
                    productid = x.Product.Id,
                    productname = x.Product.Name,
                    categoryname = _db.Categories.FirstOrDefault(category=>category.Id == x.Product.CategoryId).Name,
                    count = x.Count,
                    deliveryandprice = x.DeliveryDetails.Delivery.Name + ":" + x.DeliveryDetails.Price,
                    status = x.Status,
                    beforeprice = x.Product.Price,
                    afterprice = x.Product.Price,
                    totalprice = x.Price,
                    orderdetailid = x.Id,
                }).ToList();
                
            
            return View(obj);
        }

        //public async IActionResult Rate(string productid, string Content , float? Rate)
        //{
        //    var user = await _userManager.GetUserAsync(User);

        //}
        public IActionResult CancelOrder(string id)
        {
            try
            {
                var o = _db.OrderDetails.Find(id);
                if(o.Status==OrderDetailStatus.unconfirm.ToString())
                {
                    o.Status = OrderDetailStatus.cancelled.ToString();
                    _db.Update(o);
                    _db.SaveChanges();
                    return Json(new { success = true, message = "đã hủy đơn hàng thành công" });
                }
                else
                    return Json(new { success = false, message = "không thể hủy được đơn hàng nữa,vì đơn hàng vừa được xác nhận bởi người bán" });

            }
            catch (Exception e)
            {

                return Json(new { success = true, message = e.Message });
            }
        }
        
        public async Task<IActionResult> ShopChannel()
        {
            var curuser = await _userManager.GetUserAsync(User);
            //check shop exits
            var shop = _db.Shops.FirstOrDefault(x => x.ApplicationUserId == curuser.Id);
            //shop chưa tạo
           
            if (shop == null)
            {
                var CanCreateShop = await _userManager.IsEmailConfirmedAsync(curuser);
                if (CanCreateShop)
                {
                    var newshop = new Shop() { ApplicationUserId = curuser.Id, Name = curuser.Name, ImgUrl = "https://picsum.photos/200/300",Description="",IsConfirm=false };
                    _db.Shops.Add(newshop);
                    _db.SaveChanges();
                    return Json(new { status = true, message = "Wait For Admin Confirm Your Shop" });
                }
                else
                    return Json(new { status = false, message = "Please Confirm your mail to create shop" });
            }
            else
            {
                if (shop.IsConfirm)
                {
                    return Json(new { status = true, message = "OK", url = "/Seller" });
                }
                return Json(new { status = false, message = "Your Shop is pending or has been lock" });
            }    
        }
        public async Task<IActionResult> ShipChannel()
        {
            var curuser = await _userManager.GetUserAsync(User);
           
            
            if (curuser.ShipperRequest == ShipperRequest.Block)
            {
                return Json(new { status = false, message = "Bạn đã bị block" });
            }
            if (curuser.ShipperRequest == ShipperRequest.Pending)
            {
                return Json(new { status = true, message = "Đợi admin duyệt" });
            }
            if (curuser.ShipperRequest == ShipperRequest.Approved)
            {
                return Json(new { status = true, message = "Bạn đã là shipper" });
            }
            var CanCreateShop = await _userManager.IsEmailConfirmedAsync(curuser);
            if (CanCreateShop)
            {
                curuser.ShipperRequest = ShipperRequest.Pending;
                await _userManager.UpdateAsync(curuser);
                return Json(new { status = true, message = "Đợi admin xác nhận" });
            }
            else
                return Json(new { status = false, message = "Xác nhận mail để làm shipper" });

            
        }
    }
}

MilkTeaECommerce/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    @*<link href="~/Admin/DataTables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Admin/DataTables/css/jquery.dataTables.css" rel="stylesheet" />*@
    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Admin/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- Select 2-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    @RenderSection("Header", required: false)

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Admin">
                <div class="sidebar-brand-icon rotate-n-15">
                    <img src="/images/Logo.png" class="img-fluid" />
                </div>
                <div class="sidebar-brand-text mx-3">Admin </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Trang chủ</span>
                </a>
            </li>
            <!-- Nav Item - User Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-users"></i>
                    <span>Quản lí người dùng</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>
                        <a class="collapse-item" asp-area="Admin" asp-controller="User" asp-action="Create">Tạo người dùng</a>
                        <a class="collapse-item" asp-area="Admin" asp-controller="User" asp-action="Index">Danh sách người dùng</a>

                    </div>
                </div>
            </li>
            <!-- Nav Item - Product Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProduct"
                   aria-expanded="true" aria-controls="collapseProduct">
                    <i class="fas fa-coffee"></i>
                    <span>Quản lí sản phẩm</span>
                </a>
                <div id="collapseProduct" class="collapse" aria-labelledby="headingProduct" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>
                        <a class="collapse-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Quản Lí danh mục</a>
                        <a class="collapse-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Danh sách sản phẩm</a>

                    </div>
                </div>
            </li>
            <!-- Nav Item - Bill Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBill"
                   aria-expanded="true" aria-controls="collapseBill">
                    <i class="fas fa-file-invoice"></i>
                    <span> Quản lí đơn hàng</span>
                </a>
                <div id="collapseBill" class="collapse" aria-labelledby="headingBill" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>
                        <a class="collapse-item" asp-area="Admin" asp-controller="Deliveries" asp-action="Index">Quản lí đơn vị vận chuyển</a>
                        <a class="collapse-item" asp-area="Admin" asp-controller="order" asp-action="Index">Danh sách đơn hàng</a>

                    </div>
                </div>
            </li>
            <!-- Nav Item - Discount Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseDiscount"
                   aria-expanded="true" aria-controls="collapseDiscount">
                    <i class="fas fa-percent"></i>
                    <span> Quản lí mã giảm giá</span>
                </a>
                <div id="collapseDiscount" class="collapse" aria-labelledby="headingDiscount" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>
                        <a class="collapse-item" asp-area="Admin" asp-controller="Discounts" asp-action="Upsert">Tạo mã giảm giá</a>
                        <a class="collapse-item" asp-area="Admin" asp-controller="Discounts" asp-action="Index">Danh sách mã giảm giá</a>

                    </div>
                </div>
            </li>
            <!-- Nav Item - Discount Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseShop"
                   aria-expanded="true" aria-controls="collapseShop">
                    <i class="fas fa-store-alt"></i>
                    <span> Quản lí cửa hàng</span>
                </a>
                <div id="collapseShop" class="collapse" aria-labelledby="headingShop" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>

                        <a class="collapse-item" asp-area="Admin" asp-controller="Shop" asp-action="Index">Danh sách cửa hàng</a>

                    </div>
                </div>
            </li>
            <!-- Nav Item - Shiper Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseShiper"
                   aria-expanded="true" aria-controls="collapseShop">
                    <i class="fas fa-shipping-fast"></i>
                    <span> Quản lí Shipper</span>
                </a>
                <div id="collapseShiper" class="collapse" aria-labelledby="headingShop" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Hành động:</h6>

                        <a class="collapse-item" asp-area="Admin" asp-controller="Shipper" asp-action="Index">Danh sách Shipper</a>

                    </div>
                </div>
            </li>



            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>



        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                  

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                      
                        

                        <!-- Nav Item - User Information -->
                        <partial name="_LoginPartial" />
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                @RenderBody()

                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; HYHT Lập trình web 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
        <div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div >
                            <div class="row">
                                <div class="col-12 mx-auto">

                                    <div class="p-5 bg-white shadow rounded-lg">
                                        <img src="https://res.cloudinary.com/mhmd/image/upload/v1557366994/img_epm3iz.png" alt="" width="200" class="d-block mx-auto mb-4 rounded-pill">

                                        <form id="importfile" enctype="multipart/form-data"  >
                                            <div id="alert-text" class="text-danger"></div>
                                            <div class="custom-file mb-3">
                                                <input type="file" class="custom-file-input" id="inputFile" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                                                <label class="custom-file-label" for="inputFile" aria-describedby="inputGroup">Choose file</label>
                                            </div>
                                            <input type="submit" class="form-control btn btn-primary" name="name" value="Upload sản phẩm" />
                                        </form>





                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                   
                </div>
            </div>
        </div>
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Admin/js/sb-admin-2.min.js"></script>
    
    @RenderSection("Scripts", required: false)
    <!-- Page level plugins -->




</body>

</html>