MilkTeaECommerce/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MilkTeaECommerce.Data;
using MilkTeaECommerce.Models;

namespace MilkTeaECommerce.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private static float average_rating_shop ;
        private static float average_rating_product ;
        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Detail(string id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "home");
            }
            else
            {
                var product = _db.Products.Include(x => x.Category).Include(x => x.Shop).Include(x=>x.Ratings).ThenInclude(x=>x.ApplicationUser).FirstOrDefault(x => x.Id == id);
                if (product != null)
                {
                    Get_Info_Of_Shop_And_Product(product);
                    var rating_shop = _db.Ratings.Include(x => x.Product).Where( x=>x.Product.ShopId == product.ShopId).ToList();
                    if(rating_shop.Count >0)
                    {
                        var average_rating_shop_calculate = (double)(rating_shop.Average(x => x.Rate));
                        average_rating_shop = Convert.ToSingle(Math.Floor(average_rating_shop_calculate));
                    }
                    else
                        average_rating_shop = 0;

                    var rating_product_of_shop = _db.Ratings.Include(x => x.Product).Where(x => x.ProductId == product.Id && x.Product.ShopId == product.ShopId).ToList();
                    if (rating_product_of_shop.Count > 0)
                    {
                        var average_rating_product_calculate = (double)(rating_product_of_shop.Average(x => x.Rate));
                        average_rating_product = Convert.ToSingle(Math.Floor(average_rating_product_calculate));
                    }
                    else
                        average_rating_product = 0;
                    return View(product);
                }
                return NotFound();
            }
        }

        public IActionResult Get_avarage_rating_shop_and_product()
        {
            // trả về điểm đánh giá của shop và của product
            return Json(new { rating_shop = average_rating_shop , rating_product = average_rating_product });
        }

        public void Get_Info_Of_Shop_And_Product(Product product)
        {
            var product_list_of_shop = _db.Products.Include(x => x.Ratings).Where(x => x.ShopId == product.Shop.ApplicationUserId).ToList();
            // số lượng sản phẩm của shop
            ViewBag.Product_Count = product_list_of_shop.Count();
            // số lượt đánh giá
            ViewBag.Rate_Count = product_list_of_shop.Select(x => x.Ratings.Count()).Sum();
            //  số lượt người đã mua sản phẩm của shop
            var list_customer_buy_product_of_shop = _db.OrderDetails.Include(x => x.Product).Where(x => x.Product.ShopId == product.Shop.ApplicationUserId && x.Status == OrderDetailStatus.deliveried.ToString()).ToList();
            ViewBag.Customer_Bought = list_customer_buy_product_of_shop.Count();
            // Phần trăm đơn hàng giao thành công( là bằng số đơn hàng có status = deliveried chia cho tổng đơn hàng có status = deliveried hoặc cancelled)
            var number_order_detail_of_shop = _db.OrderDetails.Include(x => x.Product).Where(x => x.Product.ShopId == product.Shop.ApplicationUserId && (x.Status == OrderDetailStatus.deliveried.ToString() || x.Status == OrderDetailStatus.cancelled.ToString())).Count();
            double result = 0;
            if(list_customer_buy_product_of_shop.Count == 0 && number_order_detail_of_shop == 0)
            {
                result = 1;
            }
            else
                result = (double)(list_customer_buy_product_of_shop.Count()) / (double)(number_order_detail_of_shop);
            ViewBag.Success_Percent = (result*100).ToString("0.00");

            // Số lượng đã bán của sản phẩm đang xem
            ViewBag.product_selled_count = _db.OrderDetails.Where(x => x.ProductId == product.Id && x.Status == OrderDetailStatus.deliveried.ToString()).Count();
            ViewBag.product_rate_count = _db.Ratings.Where(x => x.ProductId == product.Id).Count();

        }

    }
}

MilkTeaECommerce/Views/Shared/ProductPartial.cshtml
@model MilkTeaECommerce.Models.Models.ProductViewUserModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="col-md-4 product-men">
    <div class="men-pro-item simpleCart_shelfItem">
        <div class="men-thumb-item">
            <!-- hình ảnh sản phẩm-->
            <img src="@Model.ProductImgUrl" alt="" height="250" width="200" >
            <div class="men-cart-pro">
                <div class="inner-men-cart-pro">
                    <!-- link về info sản phẩm-->
                    <a asp-action="detail" asp-controller="Product" asp-route-id="@Model.ProductId" class="link-product-add-cart">Quick View</a>
                </div>
            </div>
            <span class="product-new-top">New</span>

        </div>
        <div class="item-info-product ">
            <h4>
                <a href="single.html">@Model.ProductName</a>
            </h4>
            <div class="info-product-price">
                <!-- giảm giá-->
                <span class="item_price">@Model.Price VND</span>
                <del>@Model.OldPrice VND</del>
            </div>
            <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                <form action="#" method="post">
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <input type="hidden" name="cmd" value="_cart" />
                        <input type="hidden" name="add" value="@Model.ProductId" />
                        <input type="hidden" name="shipping" value="@Model.ProductImgUrl" />
                        <input type="hidden" name="item_name" value="@Model.ProductName" />
                        <input type="hidden" name="amount" value="@Model.OldPrice" />
                        <input type="hidden" name="discount_amount" value="@Model.Price" />
                        <input type="hidden" name="currency_code" value="VND" />
                        <input type="hidden" name="return" value=" " />
                        <input type="hidden" name="cancel_return" value=" " />
                        <input type="submit" name="submit" value="Add to cart" class="button" />
                    </fieldset>
                </form>
            </div>

        </div>
    </div>
</div>

MilkTeaECommerce/Views/Shared/_BannerPartial.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        <li data-target="#myCarousel" data-slide-to="3" class=""></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    @*<h3>
                        Big
                        <span>Save</span>
                    </h3>
                    <p>
                        Get flat
                        <span>10%</span> Cashback
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>*@
                </div>
            </div>
        </div>
        <div class="item item2">
            <div class="container">
                @*<div class="carousel-caption">
                    <h3>
                        Healthy
                        <span>Saving</span>
                    </h3>
                    <p>
                        Get Upto
                        <span>30%</span> Off
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>*@
            </div>
        </div>
        <div class="item item3">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Big
                        <span>Deal</span>
                    </h3>
                    <p>
                        Get Best Offer Upto
                        <span>20%</span>
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
        <div class="item item4">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Today
                        <span>Discount</span>
                    </h3>
                    <p>
                        Get Now
                        <span>40%</span> Discount
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

MilkTeaECommerce/Views/Shared/_OrderDetailUserPartial.cshtml
@model MilkTeaECommerce.Models.Models.OrderDetailUserViewModel


<div class="wait-confirm-items">
    <div class="item-inner">
        <div class="item-header">
            <!--đây là thông tin của shop, bao gồm ảnh và tên -->
            <!-- phải link về thông tin của shop-->
            <a href="#">
                <img class="avatar-shop" src="@Model.shopimage" alt="shop avatar" />
                <strong>@Model.shopname</strong>
            </a>
            <div>
                <!-- trạng thái có thể sửa dc-->
                @{string status = ""; }

                @{

                    if (Model.status == OrderDetailStatus.unconfirm.ToString())
                    {
                        status = "Chờ xác nhận";
                    }
                    if (Model.status == OrderDetailStatus.confirmed.ToString())
                    {
                        status = "Đã xác nhận";
                    }
                    if (Model.status == OrderDetailStatus.delivery.ToString())
                    {
                        status = "Đang Vận chuyển";
                    }
                    if (Model.status == OrderDetailStatus.deliveried.ToString() )
                    {
                        status = "Đã nhận";
                    }
                    if (Model.status == OrderDetailStatus.evaluated.ToString())
                    {
                        status = "Đã đánh giá";
                    }
                    if (Model.status == OrderDetailStatus.cancelled.ToString())
                    {
                        status = "Đã Hủy";
                    }


                }

                <span class="fa fa-truck" aria-hidden="true"> @status</span>

            </div>
        </div>
        <!-- thanh ngang-->
        <div class="breck-line"></div>
        <!-- đây là thông tin order detail-->
        <div class="item-body">
            <div style="display:flex">
                <a href="#">
                    <img class="item-img" src="@Model.productimage" alt="items" />
                </a>
                <div class="info">
                    <a href="#"><h4><strong>@Model.productname</strong></h4></a>
                    <p>Phân loại hàng : @Model.categoryname</p>
                    <p>X @Model.count</p>
                    <!--đơn vị vận chuyenr nếu có-->
                    <p>Đơn Vị Vận Chuyển : @Model.deliveryandprice</p>
                </div>
            </div>
            <!--giá từng món-->
            <div>
                <!--giá cũ từng món-->
                <p><del>@Model.beforeprice đ</del></p>
                <!--giá Khuyến mĩa từng món-->
                <h2 class="text-danger">@Model.afterprice đ</h2>
            </div>
        </div>
        <!-- nếu trạng thái giao hàng là gì thì ra cái gì-->
        <!-- Cac status = (cho xac nhan,cho lay hang,dang giao, da giao-->
        @if (Model.status == OrderDetailStatus.unconfirm.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
                <div class="text-right mt">
                   
                    <a class="btn btn-lg btn-info" onclick=CancelOrder("@Model.orderdetailid")>Hủy đơn</a>
                </div>
            </div>
        }
        else if (Model.status == OrderDetailStatus.confirmed.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
                <div class="text-right mt">
                    
                </div>
            </div>

        }
        else if (Model.status == OrderDetailStatus.delivery.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
            </div>
        }
        else if (Model.status == OrderDetailStatus.deliveried.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
                <div class="text-right mt">
                    <a class="btn btn-lg" style="background-color:#343a40 ; color:#fff" href="#">Xem chi tiết đơn hàng</a>
                    <a href="#" class="btn btn-lg btn-success" data-toggle="modal" data-target="#RatingModal" data-productid="@Model.productid" data-orderdetailid=@Model.orderdetailid>Đánh Giá</a>
                    
                </div>
            </div>
            <!-- pop up danh gia san pham-->
            <!-- đây là cho edit modal-->
        }
        else if (Model.status == OrderDetailStatus.evaluated.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
            </div>
            <div class="text-right mt">
                
                <a href="#" class="btn btn-lg btn-warning" data-toggle="modal" data-target="#RatingModalReadOnly" data-productid="@Model.productid" data-orderdetailid=@Model.orderdetailid>Xem Chi Tiết Đánh Giá</a>
               
            </div>

        }
        else if (Model.status == OrderDetailStatus.cancelled.ToString())
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
            </div>
            

        }

        @*else
        {
            <div class="item-fooder">
                <h1 class="text-right">Tổng tiền: @(Model.afterprice * Model.count)</h1>
                <div class="text-right mt">
                    <a class="btn btn-lg btn-info" href="#">Hủy đơn</a>
                </div>
            </div>
        }*@

    </div>

</div>

MilkTeaECommerce/Views/Shared/_RatingPartial.cshtml
@model MilkTeaECommerce.Models.Rating ;

@section header{
    <link href="~/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
}
@{int i = 0;}

<div style="border-bottom: 1px solid; margin-bottom:50px" >
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <img  src="@(Model.ApplicationUser.ImageUrl==null?"":Model.ApplicationUser.ImageUrl)" style="border-radius:50%;margin-right:10px" height="50" width="50" />
                    <span style="font-size:20px">@Model.ApplicationUser.Name</span>
                </div>
                
                <div class="col-md-12">
                    @{
                        if (Model.Rate != null)
                            i = (int)(Model.Rate.GetValueOrDefault());
                    }
                    @for (int j = 1; j <= i; j++)
                    {
                        <span> <i class="fas fa-star"></i></span>
                    }
                    @for (int j = 1; j <=5-i; j++)
                    {
                        <span> <i class="far fa-star"></i></span>
                    }
                </div>
                
                


            </div>
        </div>
        <div class="col-md-12">
            <p>@Model.Content</p>
        </div>
    </div>
    </div>